name: Linux

on: [push]

jobs:

  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build examples
        run: |
          bazelisk build //examples/...
      - name: remote execution
        run: |
          git clone https://github.com/bazelbuild/bazel-buildfarm /temp/bazel-buildfarm
          cd /temp/bazel-buildfarm && ./examples/bf-run start && popd
          bazelisk build --config=remote --config=linux //examples/...
