name: Linux

on: [push]

jobs:

  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build examples
        run: bazelisk build //examples/...
      - name: build workspaces
        run: cd workspaces/custom_toolchain && bazelisk build //src/...
