name: macOS

on: [push]

jobs:

  macos:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build examples
        run: |
          bazelisk build //examples/...
