name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  windows:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build examples
        run: |
          bazelisk build //examples/...
      - name: Bazel backwards compatibility
        run: |
          $Env:USE_BAZEL_VERSION = "6.4.0"
          bazelisk build //examples/...
