name: Windows

on: [push]

jobs:

  windows:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build examples
        run: |
          bazelisk build examples:all
          bazelisk build --config=legacy examples:all
