name: Windows

on: [push]

jobs:

  windows:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: build examples
        run: bazelisk build //examples/...
      - name: build custom_toolchain
        run: cd workspaces/custom_toolchain && bazelisk build //src/...
